### ISSUE TITLE
Issue with command "yarn dev"

### ISSUE THREAD

**Issue by MOBIWORK** [jellydn/moleculer-typescript-template#333]
### Describe the bug

I have executed the command "yarn dev" but encountered an error. Please help me fix it. Thank you very much

PS E:\MBW.Moleculer\demo\moleculer-demo> yarn dev
yarn run v1.22.19
$ tsup --watch --onSuccess 'node_modules/.bin/moleculer-runner --env --config dist/moleculer.config.js'
CACError: option `--env.* <value>` value is missing
    at Command.checkOptionValue (E:\MBW.Moleculer\demo\moleculer-demo\node_modules\cac\dist\index.js:417:17)
    at CAC.runMatchedCommand (E:\MBW.Moleculer\demo\moleculer-demo\node_modules\cac\dist\index.js:603:13)   
    at main (E:\MBW.Moleculer\demo\moleculer-demo\node_modules\tsup\dist\chunk-RCEDGIWE.js:223:13)
    at Object.<anonymous> (E:\MBW.Moleculer\demo\moleculer-demo\node_modules\tsup\dist\cli-default.js:12:23)
    at Module._compile (node:internal/modules/cjs/loader:1126:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1180:10)
    at Module.load (node:internal/modules/cjs/loader:1004:32)
    at Function.Module._load (node:internal/modules/cjs/loader:839:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:17:47
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Reproduction

When run command "yarn dev"

### System Info

```Shell
yarn dev
```

### Used Package Manager

yarn

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by jellydn** [comment]
Hi @MOBIWORK I have just tried and it works. Do you create .env from .env.example as the readme? https://github.com/jellydn/moleculer-typescript-template#usage

By the way, what is your nodejs version? Here is mine.

```sh
❯ fnm ls
* v16.20.0 default
* v18.17.0 lts-lates
```

**Comment by MOBIWORK** [comment]
![2023-08-14_22-33-10](https://github.com/jellydn/moleculer-typescript-template/assets/24837857/bc5169a0-7377-435e-b721-4098df657e03)
![2023-08-14_22-32-11](https://github.com/jellydn/moleculer-typescript-template/assets/24837857/0ddaaeac-8811-404d-b370-83e9a514910c)
